# Generated by Django 5.1.7 on 2025-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearancePurpose',
            fields=[
                ('clearance_purpose_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose_name', models.CharField(max_length=120, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'clearance_purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'document_type',
                'managed': False,
            },
        ),
    ]
