# Generated by Django 5.1.7 on 2025-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildHealthDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'view_specific_child_health_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildHealthListRow',
            fields=[
                ('child_health_id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_id', models.IntegerField()),
                ('child_full_name', models.TextField()),
                ('sex', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('age', models.TextField(null=True)),
                ('family_code', models.TextField(null=True)),
                ('sitio_id', models.IntegerField(null=True)),
                ('sitio_name', models.TextField(null=True)),
                ('feeding_method_name', models.TextField(null=True)),
                ('tt_status_name', models.TextField(null=True)),
                ('tt_status_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_all_child_health_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('disease_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'disease_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseTypeRow',
            fields=[
                ('disease_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_name', models.TextField()),
            ],
            options={
                'db_table': 'disease_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthMonitoringRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'view_specific_child_all_growth_monitoring_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImmunizationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'view_specific_child_immunization_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalCheckupRow',
            fields=[
                ('checkup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trimester_name', models.TextField()),
                ('date_of_checkup', models.DateField(null=True)),
                ('aog_weeks', models.IntegerField(null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure', models.CharField(max_length=50, null=True)),
                ('fetal_heart_rate', models.IntegerField(null=True)),
                ('laboratory_results', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('date_of_visit', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'view_specific_maternal_all_checkup_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalDeliveryOutcomeRow',
            fields=[
                ('outcome_id', models.IntegerField(primary_key=True, serialize=False)),
                ('outcome_type', models.TextField()),
                ('delivery_type', models.TextField()),
                ('place_delivery_type', models.TextField()),
                ('ownership_type', models.TextField(null=True)),
                ('others_description', models.TextField(null=True)),
                ('birth_attendant', models.TextField()),
                ('other_attendant', models.TextField(null=True)),
                ('time_of_delivery', models.TimeField(null=True)),
                ('date_terminated', models.DateField(null=True)),
                ('recorded_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_delivery_outcome_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalDiseaseSurveillanceRow',
            fields=[
                ('ids_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_type_id', models.IntegerField()),
                ('disease_name', models.TextField()),
                ('screening_date', models.DateField(null=True)),
                ('result', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_disease_surveillance_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalHealthDetailRow',
            fields=[
                ('maternal_health_id', models.IntegerField(primary_key=True, serialize=False)),
                ('maternal_id', models.IntegerField()),
                ('registration_date', models.DateTimeField()),
                ('family_code', models.TextField()),
                ('nhts_status', models.BooleanField()),
                ('full_name', models.TextField()),
                ('dob', models.DateField()),
                ('age_years', models.IntegerField()),
                ('full_address', models.TextField()),
                ('address_landmark', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
            ],
            options={
                'db_table': 'view_specific_maternal_health_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalHealthListRow',
            fields=[
                ('maternal_health_id', models.IntegerField(primary_key=True, serialize=False)),
                ('maternal_id', models.IntegerField()),
                ('maternal_full_name', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('record_status', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_all_maternal_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalImmunizationStatusTrackRow',
            fields=[
                ('immu_status_track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_dose', models.BooleanField(null=True)),
                ('first_dose_date', models.DateField(null=True)),
                ('second_dose', models.BooleanField(null=True)),
                ('second_dose_date', models.DateField(null=True)),
                ('third_dose', models.BooleanField(null=True)),
                ('third_dose_date', models.DateField(null=True)),
                ('fourth_dose', models.BooleanField(null=True)),
                ('fourth_dose_date', models.DateField(null=True)),
                ('fifth_dose', models.BooleanField(null=True)),
                ('fifth_dose_date', models.DateField(null=True)),
                ('fim_status', models.BooleanField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'view_specific_maternal_immunization_status_track_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalLaboratoryScreeningRow',
            fields=[
                ('lab_screening_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_type_id', models.IntegerField()),
                ('test_name', models.TextField()),
                ('test_date', models.DateField(null=True)),
                ('result', models.TextField(null=True)),
                ('iron_tablet_given_date', models.DateField(null=True)),
                ('iron_tablet_quantity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_laboratory_screening_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalMedicalConditionRow',
            fields=[
                ('mmh_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_medical_history_name', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_medical_condition_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalPostpartumVisitRow',
            fields=[
                ('postpartum_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_visit', models.DateField(null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('laboratory_notes', models.TextField(null=True)),
                ('recorded_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_postpartum_visit_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalSupplementRow',
            fields=[
                ('maternal_supplement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplement_type_id', models.IntegerField()),
                ('supplement_name', models.TextField()),
                ('date_given', models.DateField(null=True)),
                ('number_of_tablets', models.IntegerField(null=True)),
                ('trimester_name', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_supplements_record_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaternalSurgicalHistoryRow',
            fields=[
                ('msh_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_surgical_history_name', models.TextField()),
                ('date_of_surgery', models.DateField(null=True)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_specific_maternal_all_surgical_history_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalConditionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'view_specific_child_all_medical_condition_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObstetricalHistoryRow',
            fields=[
                ('obs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gravida', models.IntegerField(null=True)),
                ('para', models.IntegerField(null=True)),
                ('abortion', models.IntegerField(null=True)),
                ('last_menstrual_period', models.DateField(null=True)),
                ('expected_date_of_delivery', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'view_obstetrical_history_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurgicalHistoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'view_specific_child_all_surgical_history_row',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestTypeRow',
            fields=[
                ('test_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.TextField()),
            ],
            options={
                'db_table': 'Test_Type',
                'managed': False,
            },
        ),
    ]
