# Generated by Django 5.1.7 on 2025-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildGrowthMonitoring',
            fields=[
                ('cgm_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_health_id', models.IntegerField()),
                ('date_of_visit', models.DateTimeField(auto_now_add=True)),
                ('age_in_months', models.IntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resp_rate', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'child_growth_monitoring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildHealthRecord',
            fields=[
                ('child_health_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_id', models.IntegerField()),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('birth_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('place_of_delivery', models.CharField(blank=True, max_length=200, null=True)),
                ('address_landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('tt_status_of_mother', models.IntegerField(blank=True, null=True)),
                ('tt_status_date', models.DateField(blank=True, null=True)),
                ('newborn_screening_status', models.BooleanField(blank=True, null=True)),
                ('newborn_screening_status_date', models.DateField(blank=True, null=True)),
                ('feeding_method_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'child_health_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildImmunizationRecord',
            fields=[
                ('immunization_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_health_id', models.IntegerField()),
                ('vaccine_type_id', models.IntegerField()),
                ('dose_type_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'child_immunization_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChildSupplementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_health_id', models.IntegerField()),
                ('supplement_id', models.IntegerField()),
                ('age_in_months', models.IntegerField()),
                ('date_given', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'child_supplement_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_description', models.TextField()),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoseType',
            fields=[
                ('dose_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'dose_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExclusiveBreastfeed',
            fields=[
                ('eb_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_health_id', models.IntegerField()),
                ('month_id', models.IntegerField()),
                ('date_assessed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exclusive_breastfeed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_code', models.CharField(max_length=20, unique=True)),
                ('household_id', models.IntegerField()),
                ('household_type_id', models.IntegerField()),
                ('family_head_id', models.IntegerField()),
                ('respondent_id', models.IntegerField()),
                ('respondent_relationship_to_fh_id', models.IntegerField(blank=True, null=True)),
                ('ip_status', models.BooleanField(default=False)),
                ('ip_tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('nhts_status', models.BooleanField(default=False)),
                ('water_source_type_id', models.IntegerField()),
                ('toilet_facility_type_id', models.IntegerField()),
                ('waste_management_type_id', models.IntegerField()),
                ('waste_other_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('family_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_member_code', models.CharField(max_length=20, unique=True)),
                ('family_id', models.IntegerField()),
                ('resident_id', models.IntegerField()),
                ('rth_id', models.IntegerField()),
                ('rtf_id', models.IntegerField()),
                ('philhealthid_number', models.CharField(blank=True, max_length=50, null=True)),
                ('membership_type', models.CharField(blank=True, max_length=1, null=True)),
                ('philhealth_category_id', models.IntegerField(blank=True, null=True)),
                ('nutrition_status_id', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.IntegerField()),
            ],
            options={
                'db_table': 'family_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeedingMethod',
            fields=[
                ('feeding_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'feeding_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FPMethod',
            fields=[
                ('fp_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'fp_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FPStatus',
            fields=[
                ('fp_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'fp_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralHealthFemale',
            fields=[
                ('ghtf_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_member_id', models.IntegerField()),
                ('quarter_id', models.IntegerField()),
                ('medical_history_ids', models.JSONField(blank=True, null=True)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('fp_method_yn', models.BooleanField(blank=True, null=True)),
                ('fp_method_id', models.IntegerField(blank=True, null=True)),
                ('fp_status_id', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField()),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('alcohol_drinker', models.BooleanField(blank=True, null=True)),
                ('sexually_active', models.BooleanField(blank=True, null=True)),
                ('age_of_menarche', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.IntegerField()),
            ],
            options={
                'db_table': 'general_health_female',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralHealthMale',
            fields=[
                ('ghtm_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_member_id', models.IntegerField()),
                ('quarter_id', models.IntegerField()),
                ('medical_history_ids', models.JSONField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField()),
                ('smoker', models.BooleanField(blank=True, null=True)),
                ('alcohol_drinker', models.BooleanField(blank=True, null=True)),
                ('sexually_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.IntegerField()),
            ],
            options={
                'db_table': 'general_health_male',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('household_number', models.CharField(max_length=20, unique=True)),
                ('house_ownership_id', models.IntegerField(blank=True, null=True)),
                ('house_type_id', models.IntegerField(blank=True, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('household_head_id', models.IntegerField()),
                ('respondent_id', models.IntegerField()),
                ('respondent_relationship_to_hh_id', models.IntegerField(blank=True, null=True)),
                ('visited_by_id', models.IntegerField()),
                ('is_visited', models.BooleanField(default=False)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseholdType',
            fields=[
                ('household_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'household_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseOwnershipType',
            fields=[
                ('house_ownership_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('house_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'house_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryType',
            fields=[
                ('medical_history_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'medical_history_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_sequence_name', models.CharField(max_length=20, unique=True)),
                ('month_number', models.IntegerField()),
            ],
            options={
                'db_table': 'month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionStatus',
            fields=[
                ('nutrition_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrition_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhilhealthCategory',
            fields=[
                ('philhealth_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'philhealth_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipToHouseholdHead',
            fields=[
                ('rth_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relationship_to_householdhead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentMedicalHistory',
            fields=[
                ('rmh_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_health_id', models.IntegerField()),
                ('medical_history_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resident_medical_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentSurgicalHistory',
            fields=[
                ('rsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_health_id', models.IntegerField()),
                ('surgical_history_name', models.CharField(max_length=200)),
                ('date_of_surgery', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resident_surgical_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('supplement_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplement_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'supplements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToiletFacilityType',
            fields=[
                ('toilet_facility_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'toilet_facility_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTStatus',
            fields=[
                ('tt_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_code', models.CharField(max_length=10, unique=True)),
                ('tt_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tt_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('vaccine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100, unique=True)),
                ('at_birth', models.BooleanField(default=False)),
                ('first_dose', models.BooleanField(default=False)),
                ('second_dose', models.BooleanField(default=False)),
                ('third_dose', models.BooleanField(default=False)),
                ('interval_between_doses', models.DurationField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccine_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteManagementType',
            fields=[
                ('waste_management_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waste_management_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterSourceType',
            fields=[
                ('water_source_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'water_source_type',
                'managed': False,
            },
        ),
    ]
