"""
Django settings for lambo project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# --- Sessions ---
SESSION_COOKIE_AGE = 300
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pmxq2n=0rxlqw^k4cvqlz!uc*!+9(epm$y_gl=-r-4lzzldo*s'

# TIMEOUT SETTINGS
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
REQUEST_TIMEOUT = 30  # 30 seconds


load_dotenv()
# ---- Supabase storage ----
ENV = os.environ.get("ENV", "development")  # "development" | "production"
if ENV == "production":
    DEBUG = False
    print("Running in production mode")
    print(f"ENV value: Inside Production Block {ENV}")
    ALLOWED_HOSTS = ['lambo-web-5mka.onrender.com']
else:
    DEBUG = True
    print("Running in development mode")
    print(f"ENV value: Inside Development Block {ENV}")
    ALLOWED_HOSTS = ['*']

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tailwind', # Tailwind CSS
    'theme', # Theme App

    'authentication', # Authentication App
    'personnels_module', # Personnels Module
    'resident_profiling_module', # Resident Profiling Module
    'admin_module',
    'captain_module',
    'treasurer_module',
    'nurse_module',
    'secretary_module',
    'bhw_module',
    'household_module',
    'certificate_issuance_module',

    'django_browser_reload', # Browser Reload

    'rest_framework', # Django REST Framework
    'corsheaders', # CORS Headers
    'resident_api', # Resident API
]

# Django REST API
# MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

CORS_ALLOW_ALL_ORIGINS = True

# Tailwind CSS
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    '127.0.0.1',
]

# NPM_BIN_PATH = 'C:/Program Files/nodejs/npm.cmd'

# ---- Tailwind / npm binary path ----
if ENV == "production":
    NPM_BIN_PATH = "/usr/bin/npm"
else:
    NPM_BIN_PATH = 'C:/Program Files/nodejs/npm.cmd'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_browser_reload.middleware.BrowserReloadMiddleware',
    
    
]

MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'lambo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lambo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

if 'CI' in os.environ:  # Check if running in CI environment
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',  # Use SQLite for CI tests
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),

            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'CONN_MAX_AGE': 0,  # Close connections immediately after each request
            'OPTIONS': {
                'client_encoding': 'UTF8',
                'sslmode': 'require',
                'options': '-c timezone=Asia/Manila',
                # connection settings
                'connect_timeout': 10,
                'keepalives': 1,
                'keepalives_idle': 30,
                'keepalives_interval': 10,
                'keepalives_count': 5,
            },
        }
    }

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
        'household_module': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "auth.resolve": {  # matches logger name above
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_ANON_KEY') #client operations
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY') #admin operations

# Bucket for resident docs (from your Supabase screenshot)
SUPABASE_BUCKET_DOCS = os.environ.get("SUPABASE_BUCKET_DOCS", "resident-documents")

# Public only in dev, private in production
SUPABASE_BUCKET_DOCS_PUBLIC = os.environ.get(
    "SUPABASE_BUCKET_DOCS_PUBLIC",
    "true" if ENV == "development" else "false"
).lower() == "true"

# Signed URL lifetime for private docs
SUPABASE_SIGNED_SECONDS = int(os.environ.get("SUPABASE_SIGNED_SECONDS", "300"))

# # 📧 Email configuration
# EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.sendgrid.net')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'apikey') 
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "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")
# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
# EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))

# 📧 Email configuration (SendGrid)
# Use the official SendGrid backend so emails are sent via HTTPS, not blocked SMTP
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = "LAMBO No-reply <lambonoreply@gmail.com>"
SITE_ORIGIN = os.getenv("SITE_ORIGIN", "https://lambo-web-5mka.onrender.com")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "15"))

# if SUPABASE_URL and SUPABASE_SERVICE_KEY:
#     supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
# else:
#     supabase = None

# Media files configuration for Supabase
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ID ANALYZER API
ID_ANALYZER_API_KEY = os.getenv('ID_ANALYZER_API_KEY')
OCR_BACKEND = os.getenv('OCR_BACKEND', 'idanalyzer') #default to idanylzer if not set
ENABLE_OCR_VALIDATION = os.environ.get('ENABLE_OCR_VALIDATION', 'true').lower() == 'true'
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # restrict/disable drf browsable api in production
    REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': [
            'rest_framework.renderers.JSONRenderer',
        ],
    }

# DJANGO CACHE CONFIGURATION - 

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # In-memory cache
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of cached items
        }
    }
}

