from django.urls import path
from . import views

app_name = 'bhw_module'

urlpatterns = [
     path('', views.bhw_dashboard, name='bhw_dashboard'),
     path('householdList/', views.householdList, name='householdList'),
     path('householdView/', views.householdView, name='householdView'),
     path('householdVisit/', views.householdVisit, name='householdVisit'),
     path('household/update/', views.update_household, name='householdUpdate'),
     path('family/insert/', views.insert_family, name='familyInsert'),
     path("family/mark-visit/", views.mark_family_visit, name="familyVisitMark"),
     path('familyMember/insert/', views.insert_family_member, name='familyMemberInsert'),
     path('family/update/', views.update_family, name='familyUpdate'),
     path('family/deactivate/', views.deactivate_family, name='familyDeactivate'),
     path('household/activate/', views.reactivate_household, name='householdReactivate'),
     path('household/deactivate/', views.deactivate_household, name='householdDeactivate'),
     path("household/visit/mark/", views.mark_household_visit, name="householdVisitMark"),
     path('family/update/member/', views.update_family_member, name='familyMemberUpdate'),
     path('family/remove/member/', views.remove_family_member, name='familyMemberRemove'),
     path('api/resident-links', views.resident_links_list_api, name='residentLinksListApi'),
     path('api/resident-links/insert', views.resident_link_insert, name='residentLinkInsert'),
     path('api/resident-links/remove', views.resident_link_remove, name='residentLinkRemove'),
     path('family/insert/general-health/', views.insert_general_health, name='insertGeneralHealth'),
     path('family/update/general-health/', views.update_general_health, name='updateGeneralHealth'),
     path("general-health", views.general_health_get_api, name="generalHealthGetApi"),
     path('api/child/search/', views.child_search_api, name='child_search_api'),
     path('residentList/', views.residentList),
     path('residentAdd1/', views.residentAdd1),
     path('residentAdd2/', views.residentAdd2),
     path('residentAdd3/', views.residentAdd3),
     path('residentAdd4/', views.residentAdd4),
     path('childList/', views.childList, name='childList'),
     path('addchild1/', views.addchild1, name='addchild1'),
     path('addchild2/', views.addchild2, name='addchild2'),
     path('addchild3/', views.addchild3, name='addchild3'),
     path('addchild4/', views.addchild4, name='addchild4'),
     path('childView/', views.childView, name='childView'),
     path('child/add-medical-condition/', views.add_medical_condition, name='addMedicalCondition'),
     path('child/add-surgical-history/', views.add_surgical_history, name='addSurgicalHistory'),
     path('child/add-supplement/', views.add_child_supplement, name='addChildSupplement'),
     path('child/add-growth-monitoring/', views.add_child_growth_monitoring, name='addChildGrowthMonitoring'),
     path('child/add-exclusive-breastfeed/', views.add_exclusive_breastfeed, name='addExclusiveBreastfeed'),
     path('child/update/', views.update_child_health_record, name='updateChildHealthRecord'),
     path('genInfo/', views.genInfo, name='genInfo'),
     path('maternalList/', views.maternalList, name='maternalList'),
     path('maternalAdd/', views.maternalAdd, name='maternalAdd'),
     path('maternalView/', views.maternalView, name='maternalView'),
     path('maternal/add-obstetrical-history/', views.add_obstetrical_history, name='addObstetricalHistory'),
     path('maternal/add-medical-condition/', views.add_maternal_medical_condition, name='addMaternalMedicalCondition'),
     path('maternal/add-surgical-history/', views.add_maternal_surgical_history, name='addMaternalSurgicalHistory'),
     path('maternal/add-immunization/', views.add_maternal_immunization, name='addMaternalImmunization'),
     path('HouseholdAdd/', views.HouseholdAdd, name='HouseholdAdd'),
     path('residents/search/', views.resident_search_api, name='resident_search_api'),
     path('api/mother/search/', views.mother_search_api, name='mother_search_api'),
     path('maternal/add-disease-screening/', views.add_disease_screening, name='addDiseaseScreening'),
     path('maternal/add-lab-screening/', views.add_lab_screening, name='addLabScreening'),
     path('maternal/add-checkup-record/', views.add_checkup_record, name='addCheckupRecord'),
     path('maternal/add-supplement/', views.add_maternal_supplement, name='addMaternalSupplement'),
     path('maternal/add-deworming/', views.add_maternal_deworming, name='addMaternalDeworming'),
     path('maternal/add-delivery-outcome/', views.add_delivery_outcome, name='addDeliveryOutcome'),
     path('maternal/add-postpartum-visit/', views.add_postpartum_visit, name='addPostpartumVisit'),
     # PDF Generation endpoints
     path('household_list/pdf/', views.generate_household_list_pdf, name='generate_household_list_pdf'),
     path('household/<int:household_id>/pdf/', views.generate_household_detail_pdf, name='generate_household_detail_pdf'),
]

