from django.urls import path
from . import views

app_name = 'bhw_module'

urlpatterns = [
     path('', views.bhw_dashboard, name='bhw_dashboard'),
     path('householdList', views.householdList),
     path('addHousehold1', views.addHousehold1),
     path('addHousehold2', views.addHousehold2),
     path('addHousehold3', views.addHousehold3),
     path('addHousehold4', views.addHousehold4),
     path('addHousehold5', views.addHousehold5),
     path('householdView', views.householdView),
     path('householdVisit', views.householdVisit),
     path('memberProfile1', views.memberProfile1),
     path('memberProfile2', views.memberProfile2),
     path('residentList', views.residentList),
     path('residentUpdate', views.residentUpdate),
     path('residentUpdate1', views.residentUpdate1),
     path('residentAdd1', views.residentAdd1),
     path('residentAdd2', views.residentAdd2),
     path('residentAdd3', views.residentAdd3),
     path('residentAdd4', views.residentAdd4),
     path('childList', views.childList),
     path('addchild1', views.addchild1),
     path('addchild2', views.addchild2),
     path('addchild3', views.addchild3),
     path('childView', views.childView),
     path('childUpdate', views.childUpdate),
     path('childImmunization', views.childImmunization),
     path('childImmunizationAdd', views.childImmunizationAdd),   
     path('childSupplement', views.childSupplement),
     path('childSupplementAdd', views.childSupplementAdd),
     path('childGrowth', views.childGrowth),
     path('childGrowthAdd', views.childGrowthAdd),
     path('childSurgical', views.childSurgical),
     path('childSurgicalAdd', views.childSurgicalAdd),
     path('childMedicalAdd', views.childMedicalAdd),
     path('genInfo', views.genInfo),
     path('genInfoMore', views.genInfoMore),
]
